help_plus = """
HERE ARE THE BAN CODES FOR [EDITH -X](https://t.me/EdithXscanner):
• `ED_X_01` - RAID PARTICIPANT
• `ED_X_02` - RAID/SPAM INFLAMMER
• `ED_X_03` - SCAMMER
• `ED_X_04` - SPAM ADDING MEMBER
• `ED_X_05` -  ABUSE SPAM 
• `ED_X_06` - NSFW SPAMMER
• `ED_X_07` - IMPERSONATION
• `ED_X_08` - MD/BTC SCAM
• `ED_X_09` - ADDING SPAMBOTS
• `ED_X_10` - ILLEGAL
• `ED_X_11` - PHISHING
• `ED_X_12` -  FRAUD PROMOTION  (ANY KIND)
• `ED_X_13` - CYBER THREATENING/CYBER BULLY 
• `ED_X_14` - CHILD ABUSE 
• `ED_X_15` - BAN EVASION 
• `ED_X_16` - SPAMBOT
• `ED_X_17` - RAID INITIALIZOR
• `ED_X_18` - CRIMINAL ACT
THIS SCANNER BANS ONLY APPLY TO YOUR GROUP IF U ARE USING ANY ONE OF THE BOTS IN [THIS LIST](https://t.me/EdithXinfo/12)
"""


__plugin_name__ = "Bancodes"
